using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace RequestSpark.Web.Models;

/// <summary>
/// Current startup data status for the RequestSpark host application.
/// </summary>
public sealed class InitializationStatusResponse
{
    /// <summary>UTC timestamp when the status payload was generated.</summary>
    [Description("UTC timestamp when the initialization status was generated.")]
    public DateTime Timestamp { get; set; }

    /// <summary>Indicates whether startup initialization completed.</summary>
    [Description("Indicates whether startup initialization completed successfully.")]
    [DefaultValue(true)]
    public bool Initialized { get; set; }

    /// <summary>Details about the seeded sample Postman collection.</summary>
    [Description("Details about the seeded sample Postman collection.")]
    public SampleCollectionInitializationStatus SampleCollection { get; set; } = new();

    /// <summary>Details about the seeded default test configuration.</summary>
    [Description("Details about the seeded default test configuration.")]
    public InitialConfigurationStatus InitialConfiguration { get; set; } = new();

    /// <summary>Aggregate counts for stored configuration data.</summary>
    [Description("Aggregate counts for stored configuration data.")]
    public InitializationTotals Totals { get; set; } = new();
}

/// <summary>
/// Status of the seeded sample collection.
/// </summary>
public sealed class SampleCollectionInitializationStatus
{
    /// <summary>Whether the sample collection exists.</summary>
    [Description("Whether the sample collection exists in local storage.")]
    public bool Exists { get; set; }

    /// <summary>Stored collection identifier.</summary>
    [Description("Stored collection identifier, if the sample collection exists.")]
    public string? Id { get; set; }

    /// <summary>Stored collection name.</summary>
    [Description("Stored collection name, if the sample collection exists.")]
    public string? Name { get; set; }

    /// <summary>Number of requests in the sample collection.</summary>
    [Description("Number of requests discovered in the sample collection.")]
    [Range(0, int.MaxValue)]
    public int RequestCount { get; set; }
}

/// <summary>
/// Status of the seeded default test configuration.
/// </summary>
public sealed class InitialConfigurationStatus
{
    /// <summary>Whether the initial configuration exists.</summary>
    [Description("Whether the default RequestSpark configuration exists in local storage.")]
    public bool Exists { get; set; }

    /// <summary>Stored configuration identifier.</summary>
    [Description("Stored configuration identifier, if the default configuration exists.")]
    public string? Id { get; set; }

    /// <summary>Stored configuration name.</summary>
    [Description("Stored configuration name, if the default configuration exists.")]
    public string? Name { get; set; }

    /// <summary>Total request executions generated by the configuration.</summary>
    [Description("Total request executions generated by the configuration.")]
    [Range(0, int.MaxValue)]
    public int TotalTests { get; set; }

    /// <summary>Configured iteration count.</summary>
    [Description("Configured iteration count for the default run profile.")]
    [Range(0, 1000)]
    public int Iterations { get; set; }

    /// <summary>Configured maximum concurrency.</summary>
    [Description("Configured maximum number of concurrent requests.")]
    [Range(0, 100)]
    public int Concurrency { get; set; }
}

/// <summary>
/// Aggregate initialization counts.
/// </summary>
public sealed class InitializationTotals
{
    /// <summary>Total stored configurations.</summary>
    [Description("Total number of stored test configurations.")]
    [Range(0, int.MaxValue)]
    public int Configurations { get; set; }

    /// <summary>Total stored collections.</summary>
    [Description("Total number of stored Postman collections.")]
    [Range(0, int.MaxValue)]
    public int Collections { get; set; }

    /// <summary>Total active configurations.</summary>
    [Description("Number of stored configurations currently marked active.")]
    [Range(0, int.MaxValue)]
    public int ActiveConfigurations { get; set; }
}

/// <summary>
/// Development diagnostics for stored configurations.
/// </summary>
public sealed class DebugConfigurationsResponse
{
    /// <summary>UTC timestamp when the diagnostics payload was generated.</summary>
    [Description("UTC timestamp when the debug configuration payload was generated.")]
    public DateTime Timestamp { get; set; }

    /// <summary>Total configurations in local storage.</summary>
    [Description("Total number of configurations in local storage.")]
    [Range(0, int.MaxValue)]
    public int TotalConfigurations { get; set; }

    /// <summary>Stored configuration summaries.</summary>
    [Description("Stored configuration summaries with counts and edit links.")]
    public List<DebugConfigurationSummary> Configurations { get; set; } = new();
}

/// <summary>
/// Development summary for one stored configuration.
/// </summary>
public sealed class DebugConfigurationSummary
{
    /// <summary>Configuration identifier.</summary>
    [Description("Stored configuration identifier.")]
    public string Id { get; set; } = string.Empty;

    /// <summary>Configuration name.</summary>
    [Description("Stored configuration name.")]
    public string Name { get; set; } = string.Empty;

    /// <summary>Configuration description.</summary>
    [Description("Optional configuration description.")]
    public string? Description { get; set; }

    /// <summary>Whether the configuration is active.</summary>
    [Description("Whether the configuration is currently active.")]
    public bool IsActive { get; set; }

    /// <summary>UTC timestamp when the configuration was created.</summary>
    [Description("UTC timestamp when the configuration was created.")]
    public DateTime CreatedAt { get; set; }

    /// <summary>Configured iteration count.</summary>
    [Description("Configured iteration count.")]
    [Range(1, 1000)]
    public int Iterations { get; set; }

    /// <summary>Configured maximum concurrency.</summary>
    [Description("Configured maximum concurrent request count.")]
    [Range(1, 100)]
    public int MaxConcurrency { get; set; }

    /// <summary>Number of target instances.</summary>
    [Description("Number of target instances configured for the run.")]
    [Range(0, int.MaxValue)]
    public int InstancesCount { get; set; }

    /// <summary>Number of test users.</summary>
    [Description("Number of users configured for the run.")]
    [Range(0, int.MaxValue)]
    public int UsersCount { get; set; }

    /// <summary>Number of request definitions.</summary>
    [Description("Number of request definitions configured for the run.")]
    [Range(0, int.MaxValue)]
    public int RequestsCount { get; set; }

    /// <summary>Edit page URL for this configuration.</summary>
    [Description("Relative URL for editing this configuration in the RequestSpark UI.")]
    public string EditUrl { get; set; } = string.Empty;
}
